export default [
  {
    id: "1",
    title: "Welcome to Post Manager",
    author: "Admin",
    content: "This is your first post. You can edit or delete it easily. 🚀",
    tags: ["intro", "welcome"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Exploring React",
    author: "Jane Doe",
    content: "React makes building UI simple and powerful. Components let us break things down beautifully.",
    tags: ["react", "javascript"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Vite is Amazing ⚡",
    author: "John Smith",
    content: "Vite provides an incredibly fast dev server and smooth developer experience.",
    tags: ["vite", "frontend"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Styling in CSS",
    author: "Aarushi",
    content: "CSS allows creativity—colors, layouts, and typography make the difference between plain and beautiful.",
    tags: ["css", "design"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "The Power of JavaScript",
    author: "Suresh",
    content: "JavaScript brings life to websites. From DOM manipulation to APIs, it’s everywhere.",
    tags: ["javascript", "webdev"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Why Learn Web Development?",
    author: "Priya",
    content: "Web development is about creativity and logic. You create things millions can use.",
    tags: ["career", "motivation"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    title: "Node.js for Beginners",
    author: "Michael",
    content: "Node.js lets JavaScript run on servers. Build fast, scalable apps with ease.",
    tags: ["node", "backend"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    title: "10 Tips for Debugging",
    author: "Kavya",
    content: "Debugging is an art. Use console.log, breakpoints, and patience to solve issues faster.",
    tags: ["debugging", "tips"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "9",
    title: "Deploying with Netlify",
    author: "David",
    content: "Netlify makes deployment super simple. Just drag & drop or connect GitHub!",
    tags: ["deploy", "netlify"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "10",
    title: "UI/UX Matters 🎨",
    author: "Ananya",
    content: "Good design isn’t just about looks—it’s about usability. Make it easy, not just pretty.",
    tags: ["ui", "ux", "design"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "11",
    title: "APIs in Web Dev",
    author: "Raj",
    content: "APIs let apps talk to each other. REST and GraphQL are the most popular approaches.",
    tags: ["api", "webdev"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "12",
    title: "The Beauty of Open Source",
    author: "Sophia",
    content: "Open source lets us learn from others, contribute, and build better tools together.",
    tags: ["opensource", "community"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "13",
    title: "React Router Made Easy",
    author: "Vikram",
    content: "React Router helps you build single-page applications with multiple routes easily.",
    tags: ["react", "router"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "14",
    title: "State Management Basics",
    author: "Emily",
    content: "State is the heart of React. Learn useState and useContext to manage data flow.",
    tags: ["react", "state"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "15",
    title: "Consistency Wins 🏆",
    author: "Aditi",
    content: "Consistency in coding, learning, and practicing is the secret to becoming a great developer.",
    tags: ["motivation", "learning"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
